In [ ]:
import pandas as pd

In [ ]:
TabelaJAS = '/GAM FIAPE - 23.09.xlsx'
df = pd.read_excel(TabelaJAS)

In [ ]:
df['Container Numbers'] = df['Container Numbers'].str.split(',')

In [ ]:
df_expanded = df.explode('Container Numbers')

In [ ]:
df_expanded['Actual Pickup'] = pd.to_datetime(df_expanded['Actual Pickup'], errors='coerce')

In [ ]:
df_expanded['Pick Up Week'] = df_expanded['Actual Pickup'].dt.isocalendar().week

In [ ]:
df_cleaned = df_expanded[['Consignee Code','Consignor Name','Consol Transport Mode','Container Numbers','Carrier Name','Pick Up Week','Actual Pickup','First Air/Sea Port','First Leg Arrival Port','Second Air/Sea Port','Second Air/Sea DischargePort','Vessel','ETD First Load','Leg 1 ATA','Vessel (Last Leg)','Leg 2 ATD','Second Air/Sea ATA']]

In [ ]:
df_cleaned = df_cleaned.drop_duplicates(subset=['Pick Up Week', 'First Air/Sea Port', 'Second Air/Sea Port',
                                                'Second Air/Sea DischargePort', 'Vessel', 'Vessel (Last Leg)'],
                                        keep='first')

In [ ]:
df['Container Numbers'] = df['Container Numbers'].apply(lambda x: [item.strip() for item in x] if isinstance(x, list) else x)

In [ ]:
#erro#
df['Consol Transport Mode'] = df['Consol Transport Mode'].str.replace('AIR', '', regex=False)

In [ ]:
#erro#
df_expanded['Actual Pickup'] = df_expanded['Actual Pickup'].dt.normalize()

In [ ]:
df_cleaned.to_excel('TabelaJASRevised.xlsx', index=False)

In [ ]:
import os

In [ ]:
print(os.getcwd())

/content

In [ ]:
display(df_cleaned)

,Consignee Code,Consignor Name,Consol Transport Mode,Container Numbers,Carrier Name,Pick Up Week,Actual Pickup,First Air/Sea Port,First Leg Arrival Port,Second Air/Sea Port,Second Air/Sea DischargePort,Vessel,ETD First Load,Leg 1 ATA,Vessel (Last Leg),Leg 2 ATD,Second Air/Sea ATA
0,FCAFIAGNA,STELLANTIS MEXICO SA DE CV,SEA,CAIU7797731,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,46,2023-11-15 11:28:00,MXVER,BRSSZ,NaN,NaN,MONTE PASCOAL,2023-11-15 07:00:00,2023-11-15 07:00:00,MONTE PASCOAL,2023-12-12 01:38:00,NaT
1,FCAFIAGNA,PRIME WHEEL MEXICO S. DE R.L. DE C.V.,SEA,MEDU7823852,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,52,2023-12-27 10:13:00,MXESE,MXZLO,MXZLO,BRSSZ,SEASPAN BREEZE,2023-12-20 00:00:00,2023-12-20 19:34:00,MSC LOS ANGELES,2024-01-08 20:18:00,2024-03-01 17:51:00
2,FCAFIAGNA,FCA (SHANGHAI) AUTO PARTS TRADING CO LTD,SEA,MSDU4250348,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,47,2023-11-23 13:42:00,CNSHA,BRSSZ,NaN,NaN,CAPE KORTIA,2023-12-01 00:00:00,2024-01-01 21:05:00,CAPE KORTIA,NaT,NaT
3,FCAFIAGNA,PRIME WHEEL MEXICO S. DE R.L. DE C.V.,SEA,MSDU8889297,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,50,2023-12-13 11:24:00,MXESE,MXZLO,MXZLO,BRSSZ,ATHOS,2023-12-06 00:00:00,2023-12-15 07:17:00,MSC LOS ANGELES,2023-12-22 04:44:00,2024-03-01 17:51:00
4,FCAFIAGNA,PRIME WHEEL MEXICO S. DE R.L. DE C.V.,SEA,MSMU7998089,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,46,2023-11-17 10:38:00,MXESE,MXZLO,MXZLO,PACTB,VANTAGE,2023-11-17 00:00:00,2023-11-21 11:06:00,ATHENS GLORY,2023-12-20 19:00:00,2024-01-13 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4698,FCAFIAGNA,DN AUTOMOTIVE CORPORATION,SEA,NaN,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,<NA>,NaT,KRPUS,BRSSZ,NaN,NaN,CONTI MAKALU,2024-10-06 16:18:00,NaT,CONTI MAKALU,NaT,NaT
4699,FCAFIAGNA,"ESTRA AUTOMOTIVE SYSTEMS CO., LTD.",SEA,NaN,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,38,2024-09-20 17:02:00,KRPUS,BRSSZ,NaN,NaN,CONTI MAKALU,2024-10-06 16:18:00,NaT,CONTI MAKALU,NaT,NaT
4702,FCAFIAGNA,FCA INTERNATIONAL OPERATIONS LLC,SEA,MEDU7643803,MSC MEDITERRANEAN SHIPPING COMPANY S.A.,38,2024-09-19 10:39:00,USORF,BRSSZ,NaN,NaN,MSC NOA,2024-09-23 00:00:00,NaT,MSC NOA,NaT,NaT
4705,FCAFIAGNA,FCA INTERNATIONAL OPERATIONS LLC,AIR,NaN,TAP AIR PORTUGAL,38,2024-09-20 16:37:00,USORD,PTLIS,PTLIS,BRREC,NaN,2024-09-22 18:00:00,2024-09-23 07:30:00,NaN,NaT,NaT
4708,FCAFIAGNA,"MITSUBISHI ELECTRIC THAI AUTO-PARTS CO., LTD.",SEA,NaN,REGIONAL CONTAINER LINES - HQ,<NA>,NaT,THBKK,SGSIN,NaN,NaN,KOTA HAPAS,2024-10-01 00:00:00,NaT,KOTA HAPAS,NaT,NaT

# Nova seção